# acidpipe.com:80.
server {
    listen 80;
    server_name acidpipe.com;

    access_log /home/linuxbrew/.linuxbrew/var/log/nginx/acidpipe.com.access_log;
    error_log  /home/linuxbrew/.linuxbrew/var/log/nginx/acidpipe.com.error_log info;

    return 301 https://github.com/acidpipe;
}

# www.acidpipe.com:80.
server {
    listen 80;
    server_name www.acidpipe.com;
    return      301 https://acidpipe.com$request_uri;
}
