# danil.kutkevich.org:80.
server {
    listen 80;
    server_name danil.kutkevich.org;

    access_log /var/log/nginx/danil.kutkevich.org.access_log;
    error_log  /var/log/nginx/danil.kutkevich.org.error_log info;

    return 301 https://github.com/danil;
}

# danil.kutkevich.org:80.
server {
    listen 80;
    server_name danil.kutkevich.org;
    return      301 http://danil.kutkevich.org$request_uri;
}
