# danil.kutkevich.ru:80.
server {
    listen 80;
    server_name danil.kutkevich.ru;

    access_log /home/linuxbrew/.linuxbrew/var/log/nginx/danil.kutkevich.ru.access_log;
    error_log  /home/linuxbrew/.linuxbrew/var/log/nginx/danil.kutkevich.ru.error_log info;

    return 301 "https://github.com/danil#start-of-content";
}
