# pfmt.acidpipe.com:80.
server {
    listen 80;
    server_name pfmt.acidpipe.com;

    access_log /var/log/nginx/pfmt.acidpipe.com.access_log;
    error_log  /var/log/nginx/pfmt.acidpipe.com.error_log info;

    return 301 https://github.com/pfmt;
}
