# pfmt.dev:80.
server {
    listen 80;
    server_name pfmt.dev;

    access_log /var/log/nginx/pfmt.dev.access_log;
    error_log  /var/log/nginx/pfmt.dev.error_log info;

    return 301 https://github.com/pfmt;
}

# www.pfmt.dev:80.
server {
    listen 80;
    server_name www.pfmt.dev;
    return      301 http://pfmt.dev$request_uri;
}
