# repostat.org:80.
server {
    listen 80;
    server_name repostat.org;

    access_log /var/log/nginx/repostat.org.access_log;
    error_log  /var/log/nginx/repostat.org.error_log info;

    return 301 https://github.org/repostat;
}

# www.repostat.org:80.
server {
    listen 80;
    server_name www.repostat.org;
    return      301 http://repostat.org$request_uri;
}
